<?php

/**
 * @file
 * Contains drupal_migrate_party.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_migrate_party_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the drupal_migrate_party module.
    case 'help.page.drupal_migrate_party':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Drupal 8 Migrate Example') . '</p>';
      return $output;

    default:
  }
}
